# CreateHostFromHostGroup.yml
# This play creates a host of a defined name from a defined hostgroup
- name: Publish and Promote the configured Content Views and Composite Content Views
  hosts: all
  gather_facts: false

  tasks:
  - name: "Create the host"
    include_tasks: tasks/create_host.yml
      
  # Don't assume the inventory_hostname is resolvable immediately
  # This is a long process so we can delay 300 seconds at start

  - name: Wait 1h for systems to come up on port 22 and contain "OpenSSH" - checking every 60s
    wait_for:
      timeout: 3600
      sleep: 60
      port: 22
      host: "{{ ansible_fqdn }}"
      search_regex: OpenSSH
      delay: 300
    connection: local
