---
# vmw_remove_all_snapshots.yml

- name: Delete all the vm snapshots for the list of hosts
  hosts: all
  vars_files:
  - vars/vault.yml
  - vars/vmware.yml
  vars:
    current_state: remove_all

  tasks:
  - include_tasks: tasks/snapshot_action.yml
    loop: "{{ host_list }}"