---
# vmw_shutdown_guest_os.yml

- name: Shutdown guest OS (poweroff) on the list of vmware hosts
  hosts: all
  vars_files:
  - vars/vault.yml
  - vars/vmware.yml
  vars: 
    current_state: shutdown-guest
 
  tasks:
  - include_tasks: tasks/power_action.yml
    loop: "{{ host_list }}"