---
# vmw_reboot_guest_os.yml

- name: Reboot the OS on the list of vmware hosts
  hosts: all
  vars_files:
  - vars/vault.yml
  - vars/main.yml
  vars: 
    current_state: reboot-guest
 
  tasks:
  - include_tasks: tasks/power_action.yml
    loop: "{{ query('inventory_hostnames', 'all') }}"
