---

# This determines if we should publish a content view version
# based on whether
#    skip_publish_all has been set to true
#    the content view has been published within cv.publication_threshold_hours
#    the content view has been set to force_publish
# It expects to be called in a loop with a loop variable cv

- name: "Ensure content meets publication requirements"
  ansible.builtin.set_fact:
    publish_content: false                       # default to false - only publish when necessary
    hours_since_publication: 8766                # assume the last publication was long ago.. one year - 365.25 days
    exceeded_publication_threshold_hours: false  # assume we haven't exceeded the threshold

- name: "Get content view info: {{ cv.name }}"
  redhat.satellite.content_view_info:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url }}"
    organization: "{{ satellite_organization }}"
    validate_certs: "{{ satellite_validate_certs }}"
    name: "{{ cv.name }}"
  register: cv_info
  changed_when: false

# Satellite returns the time for these values in UTC
- name: "Determine hours since last publication time"
  when: cv_info.content_view.last_published
  ansible.builtin.set_fact:
    hours_since_publication: "{{ (now(utc=true) - (cv_info.content_view.last_published[:-4] | to_datetime)).seconds / 3600 | float }}"

- name: "Print hours since last publication"
  ansible.builtin.debug:
    var: hours_since_publication

- name: "Determine if we have exceeded publication threshold hours"
  when:
    - cv.publication_threshold_hours is defined
    - (hours_since_publication|float) > (cv.publication_threshold_hours|float)
  ansible.builtin.set_fact:
    exceeded_publication_threshold_hours: true

